event{
    worker_connections 1024;
}

http{
    #rate limiter
    limit_req_zone $binary_remote_addr zone=api_limi:10m rate=10r/s;

    updtream api_backend{
        server api:8080;
    }
    server {
        listen 80;

        location /api/{
            limit_req zone=api_limit bburst=20 nodelay;

            proxy_pass          http://api_backend/;
            proxt_set_header    Host            $host;
            proxt_set_header    X-Real-IP       $remote_addr;
            procy_set_header    X-Forworded-For $proxy_add_x_forworded_for;


            #max upload size
            clien_max_body_size 20M;
        }

        location /heath{
            proxy_pass http://api_backend/health;
        }
    }
}